export const gratisMakanan = [
  {
    id: Math.random().toString(),
    image: require("../../assets/fetucini.jpg"),
    itemName: "Fetucin",
    userAva: require("../../assets/ava.png"),
    username: "Jhon Doe",
    location: 120,
    loved: 12,
  },
  {
    id: Math.random().toString(),
    image: require("../../assets/piza.webp"),
    itemName: "1 Slice Pizza",
    userAva: require("../../assets/ava1.png"),
    username: "Nina Moonk",
    location: 187,
    loved: 122,
  },
  {
    id: Math.random().toString(),
    itemName: "Letuce Salad",
    image: require("../../assets/burger1.jpg"),
    userAva: require("../../assets/ava2.png"),
    username: "Belle Delphine",
    location: 12,
    loved: 90,
  },
  {
    id: Math.random().toString(),
    image: require("../../assets/burger2.webp"),
    itemName: "Beef Burger with Cheese",
    userAva: require("../../assets/ava3.png"),
    username: "Stephenie Putri",
    location: 33,
    loved: 90,
  },
  {
    id: Math.random().toString(),
    image: require("../../assets/burger1.jpg"),
    itemName: "Sloppy Joe with Beef Patty",
    userAva: require("../../assets/ava4.png"),
    username: "Chandelier Mess",
    location: 87,
    loved: 56,
  },
];

export const gratisNonmakanan = [
  {
    id: Math.random().toString(),
    image: require("../../assets/nonmakanan/ball.jpg"),
    itemName: "Bola Voli Merk Vector",
    userAva: require("../../assets/ava.png"),
    username: "Inumaki Shoix",
    location: 22,
    loved: 2,
  },
  {
    id: Math.random().toString(),
    image: require("../../assets/nonmakanan/jaket.webp"),
    itemName: "Jaket Boomber Like New",
    userAva: require("../../assets/ava1.png"),
    username: "Itadori Yuji",
    location: 11,
    loved: 232,
  },
  {
    id: Math.random().toString(),
    image: require("../../assets/nonmakanan/pukul.webp"),
    itemName: "Baseball Bat Warna Hitam",
    userAva: require("../../assets/ava2.png"),
    username: "Sano Manjiro",
    location: 9,
    loved: 43,
  },
  {
    id: Math.random().toString(),
    image: require("../../assets/nonmakanan/shirtAnime.webp"),
    itemName: "Kaos Anime Warna Hitam",
    userAva: require("../../assets/ava3.png"),
    username: "Tim Burton",
    location: 53,
    loved: 72,
  },
  {
    id: Math.random().toString(),
    image: require("../../assets/nonmakanan/shoe1.webp"),
    itemName: "Sneaker Colorful",
    userAva: require("../../assets/ava4.png"),
    username: "Mario Bross",
    location: 64,
    loved: 96,
  },
  {
    id: Math.random().toString(),
    image: require("../../assets/nonmakanan/jaket2.webp"),
    itemName: "Jaket Lorcyful Bliss",
    userAva: require("../../assets/ava2.png"),
    username: "Brett Cavanhaugh",
    location: 91,
    loved: 76,
  },
  {
    id: Math.random().toString(),
    image: require("../../assets/nonmakanan/shoe3.jpg"),
    itemName: "Sneaker Air Jordan Full Color",
    userAva: require("../../assets/ava3.png"),
    username: "Kobe Bryant",
    location: 60,
    loved: 10,
  },
  {
    id: Math.random().toString(),
    image: require("../../assets/nonmakanan/shoe3.webp"),
    itemName: "Sneaker basketBall Series 1",
    userAva: require("../../assets/ava4.png"),
    username: "Michael Jordan",
    location: 37,
    loved: 78,
  },
];

export const freeAroundYou = [
  { longitude: 105.828171, latitude: -6.372625 },
  { longitude: 105.83122, latitude: -6.374502 },
  { longitude: 105.829372, latitude: -6.372903 },
  { longitude: 105.829974, latitude: -6.373351 },
  { longitude: 105.831649, latitude: -6.372903 },
  { longitude: 105.829651, latitude: -6.372071 },
];
