export const itemDatas = [
  {
    id: Math.random().toString(),
    category_id: 1,
    images: [require("../../assets/fetucini.jpg")],
    itemName: "Fetucin",
    userAva: require("../../assets/ava.png"),
    username: "Jhon Doe",
    location: { longitude: 105.828171, latitude: -6.372625 },
    loved: 12,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 1,
    images: [require("../../assets/piza.webp")],
    itemName: "1 Slice Pizza",
    userAva: require("../../assets/ava1.png"),
    username: "Nina Moonk",
    location: { longitude: 105.89865, latitude: -6.36282 },
    loved: 122,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 1,
    itemName: "Letuce Salad",
    images: [require("../../assets/burger1.jpg")],
    userAva: require("../../assets/ava2.png"),
    username: "Belle Delphine",
    location: { longitude: 105.861556, latitude: -6.354913 },
    loved: 90,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 1,
    images: [require("../../assets/burger2.webp")],
    itemName: "Beef Burger with Cheese",
    userAva: require("../../assets/ava3.png"),
    username: "Stephenie Putri",
    location: { longitude: 105.9028, latitude: -6.346041 },
    loved: 90,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 1,
    images: [require("../../assets/burger1.jpg")],
    itemName: "Sloppy Joe with Beef Patty",
    userAva: require("../../assets/ava4.png"),
    username: "Chandelier Mess",
    location: { longitude: 105.906237, latitude: -6.390057 },
    loved: 56,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 2,
    images: [require("../../assets/nonmakanan/ball.jpg")],
    itemName: "Bola Voli Merk Vector",
    userAva: require("../../assets/ava.png"),
    username: "Inumaki Shoix",
    location: { longitude: 105.92411, latitude: -6.32625 },
    loved: 2,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 2,
    images: [require("../../assets/nonmakanan/jaket.webp")],
    itemName: "Jaket Boomber Like New",
    userAva: require("../../assets/ava1.png"),
    username: "Itadori Yuji",
    location: { longitude: 105.838184, latitude: -6.396539 },
    loved: 232,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 2,
    images: [require("../../assets/nonmakanan/pukul.webp")],
    itemName: "Baseball Bat Warna Hitam",
    userAva: require("../../assets/ava2.png"),
    username: "Sano Manjiro",
    location: { longitude: 105.830636, latitude: -6.343653 },
    loved: 43,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 2,
    images: [require("../../assets/nonmakanan/shirtAnime.webp")],
    itemName: "Kaos Anime Warna Hitam",
    userAva: require("../../assets/ava3.png"),
    username: "Tim Burton",
    location: { longitude: 105.866046, latitude: -6.388009 },
    loved: 72,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 2,
    images: [
      require("../../assets/nonmakanan/shoe1.webp"),
      require("../../assets/nonmakanan/shoe3.webp"),
      require("../../assets/nonmakanan/shoe3.webp"),
    ],
    itemName: "Sneaker Colorful",
    userAva: require("../../assets/ava4.png"),
    username: "Mario Bross",
    location: { longitude: 105.868452, latitude: -6.339899 },
    loved: 96,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 2,
    images: [require("../../assets/nonmakanan/jaket2.webp")],
    itemName: "Jaket Lorcyful Bliss",
    userAva: require("../../assets/ava2.png"),
    username: "Brett Cavanhaugh",
    location: { longitude: 105.866046, latitude: -6.354913 },
    loved: 76,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 2,
    images: [require("../../assets/nonmakanan/shoe3.jpg")],
    itemName: "Sneaker Air Jordan Full Color",
    userAva: require("../../assets/ava3.png"),
    username: "Kobe Bryant",
    location: { longitude: 105.84233, latitude: -6.419739 },
    loved: 10,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 2,
    images: [require("../../assets/nonmakanan/shoe3.webp")],
    itemName: "Sneaker basketBall Series 1",
    userAva: require("../../assets/ava4.png"),
    username: "Michael Jordan",
    location: { longitude: 105.900416, latitude: -6.309529 },
    loved: 78,
    createdAt: Number(new Date()),
  },
  {
    id: Math.random().toString(),
    category_id: 2,
    images: [require("../../assets/nonmakanan/shoe3.webp")],
    itemName: "Sneaker basketBall Series 1",
    userAva: require("../../assets/ava4.png"),
    username: "Michael Jordan",
    location: { longitude: 105.900416, latitude: -6.309529 },
    loved: 78,
    createdAt: Number(new Date()),
  },
];

export const freeAroundYou = [
  { longitude: 105.828171, latitude: -6.372625 },
  { longitude: 105.83122, latitude: -6.374502 },
  { longitude: 105.829372, latitude: -6.372903 },
  { longitude: 105.829974, latitude: -6.373351 },
  { longitude: 105.831649, latitude: -6.372903 },
  { longitude: 105.829651, latitude: -6.372071 },
];

export const chat = [
  { userId: 1, text: "Hey there", createdAt: Number(new Date()) },
  { userId: 2, text: "Hello too", createdAt: Number(new Date()) },
  {
    userId: 2,
    text: "can i ask the item that you post ?",
    createdAt: Number(new Date()),
  },
  { userId: 1, text: "Sure you can have it", createdAt: Number(new Date()) },
  { userId: 1, text: "Where do you live ?", createdAt: Number(new Date()) },
  {
    userId: 1,
    text: "You can go to my location if you want, you can come if you want ill welcome you here in my house. its not that far from you",
    createdAt: Number(new Date()),
  },
  {
    userId: 2,
    text: "Sure ill be there in no time",
    createdAt: Number(new Date()),
  },
  {
    userId: 1,
    text: "You can go to my location if you want, you can come if you want ill welcome you here in my house. its not that far from you",
    createdAt: Number(new Date()),
  },
  {
    userId: 2,
    text: "Sure ill be there in no time",
    createdAt: Number(new Date()),
  },
  {
    userId: 1,
    text: "You can go to my location if you want, you can come if you want ill welcome you here in my house. its not that far from you",
    createdAt: Number(new Date()),
  },
  {
    userId: 2,
    text: "Sure ill be there in no time",
    createdAt: Number(new Date()),
  },
];
